OpenMethods:
  AllowInventoryOpen: true
  AllowContainerOpen: true
  AllowEnderChestOpen: true
  AllowHandOpen: true
WaitSecondsBeforeOpen: 0
OpenSound: "BLOCK_SHULKER_BOX_OPEN"
CloseSound: "BLOCK_SHULKER_BOX_CLOSE"
Messages:
  Prefix: "&8[&2OpenShulker&8] &7"
  CannotBreakContainer: "§cYou cannot break this container, since there's an opened shulker in it"
  OpenShulkerCommand:
    Syntax: "&cSyntax: &4/<LABEL> <Reload>"
    Reloaded: "The plugin was reloaded!"