# TreeMiner Configuration

# Require the player to have the treeminer.use permission to use the feature
require-permission: true

# Require the player to be sneaking/crouching to use the feature
require-sneaking: true

# Require the player to be using an axe to use the feature
require-axe: true

# Apply durability damage to the tool based on how many blocks are broken
durability-loss: true

# Maximum number of logs that can be broken at once
max-logs: 100

# List of materials that are considered logs
valid-materials:
  - OAK_LOG
  - SPRUCE_LOG
  - BIRCH_LOG
  - JUNGLE_LOG
  - ACACIA_LOG
  - DARK_OAK_LOG
  - CRIMSON_STEM
  - WARPED_STEM
  - MANGROVE_LOG
  - CHERRY_LOG
  - STRIPPED_OAK_LOG
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_BIRCH_LOG
  - STRIPPED_JUNGLE_LOG
  - STRIPPED_ACACIA_LOG
  - STRIPPED_DARK_OAK_LOG
  - STRIPPED_CRIMSON_STEM
  - STRIPPED_WARPED_STEM
  - STRIPPED_MANGROVE_LOG
  - STRIPPED_CHERRY_LOG