language: zh_cn
working_directory: server
start_command: java -Xmx16G -jar leaves.jar nogui
handler: bukkit_handler
encoding: utf8
decoding: utf8
rcon:
  enable: true
  address: 127.0.0.1
  port: 30001
  password: password
plugin_directories:
  - plugins
catalogue_meta_cache_ttl: 1200
catalogue_meta_fetch_timeout: 15
catalogue_meta_url: null
plugin_download_url: null
plugin_download_timeout: 15
plugin_pip_install_extra_args: null
check_update: false
advanced_console: true
http_proxy: null
https_proxy: null
telemetry: true
disable_console_thread: false
disable_console_color: false
custom_handlers: null
custom_info_reactors: null
watchdog_threshold: 10
handler_detection: true
debug:
  all: false
  mcdr: false
  handler: false
  reactor: false
  plugin: false
  permission: false
  command: false
  task_executor: false
  telemetry: false
